sudo: required
language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
# before_install:
#   - "./ci/before_install.sh"
install:
  - yarn install
  - sudo apt-get install jq
before_script:
  - git checkout $TRAVIS_BRANCH
script:
  - yarn test
# after_success:
#   - "./ci/deploy.sh"
# after_script:
#   - "./ci/after_script.sh"
before_deploy:
  - "./ci/scripts/git_config.sh"
deploy:
  skip_cleanup: true
  provider: script
  script: "./ci/scripts/deploy.sh"
  on:
    branch: develop